### ISSUE TITLE
Form should not disappear on submission

### ISSUE THREAD

**Issue by fostyler** [fostyler/fos-flagship#4]
After the form is submitted:
- [x] Submission should be disabled while it's submitting (if it doesn't already do that)
- [x] Form fields should reset to blank
- [x] Success message should appear above the form in a green box.  Should appear in the same location as the error message box.
- [x] Make the message disappear after a few seconds.

**Comment by codex-scribe** [comment]
Hey @fostyler when you say submission should be disabled while it's submitting, do you mean just the submit button or should all the fields kind of be grayed out?
Also is the best method for resetting the form fields to blank just to do an event default?

**Comment by fostyler** [comment]
@codex-scribe Just the submit button should be fine.  cc @LailaAli 

The` formRef.current` should have a reset() function built in.  `formRef.current.reset()`

**Comment by codex-scribe** [comment]
I talked about it with @LailaAli last week and she said to implement that.

**Comment by fostyler** [comment]
@codex-scribe added the checkbox for that. thanks
